server:
  port: 8086

spring:
  application:
    name: agent-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:}
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:localhost:8848}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 180000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
